export const modulosData = {
  Basico: [
    { id: 1, name: "Saudações", icon: "👋" },
    { id: 2, name: "Sentimentos", icon: "❤️" },
    { id: 3, name: "Animais", icon: "🐶" },
    { id: 4, name: "Comida", icon: "🍎" },
    { id: 5, name: "Cores", icon: "🎨" },
    { id: 6, name: "Família", icon: "👨‍👩‍👧" },
    { id: 7, name: "Escola", icon: "🏫" },
    { id: 8, name: "Profissões", icon: "💼" },
  ],
  Medio: [
    { id: 1, name: "Esportes", icon: "⚽" },
    { id: 2, name: "Transporte", icon: "🚗" },
    { id: 3, name: "Tecnologia", icon: "💻" },
    { id: 4, name: "Ciência", icon: "🔬" },
    { id: 5, name: "Música", icon: "🎵" },
    { id: 6, name: "Arte", icon: "🖼️" },
    { id: 7, name: "Clima", icon: "🌤️" },
    { id: 8, name: "Geografia", icon: "🌍" },
  ],
  Avancado: [
    { id: 1, name: "Política", icon: "🏛️" },
    { id: 2, name: "História", icon: "📜" },
    { id: 3, name: "Saúde", icon: "🩺" },
    { id: 4, name: "Economia", icon: "💰" },
    { id: 5, name: "Psicologia", icon: "🧠" },
    { id: 6, name: "Religião", icon: "⛪" },
    { id: 7, name: "Literatura", icon: "📚" },
    { id: 8, name: "Filosofia", icon: "🤔" },
  ],
  Tecnico: [
    { id: 1, name: "Programação", icon: "💻" },
    { id: 2, name: "Engenharia", icon: "🔧" },
    { id: 3, name: "Arquitetura", icon: "🏗️" },
    { id: 4, name: "Robótica", icon: "🤖" },
    { id: 5, name: "Matemática", icon: "➕" },
    { id: 6, name: "Química", icon: "⚗️" },
    { id: 7, name: "Física", icon: "📐" },
    { id: 8, name: "Astronomia", icon: "🌌" },
  ],
};