const modulosData = {
  "UsoDiario": [
    { id: 1, name: "Saudações", icon: "👋" },
    { id: 2, name: "Sentimentos", icon: "❤️" },
    { id: 3, name: "Animais", icon: "🐶" },
    { id: 4, name: "Comida e bebidas", icon: "🍎" },
    { id: 5, name: "Cores", icon: "🎨" },
    { id: 6, name: "Família", icon: "👨‍👩‍👧" },
    { id: 7, name: "Escola", icon: "🏫" },
    { id: 8, name: "Profissões e Trabalho", icon: "💼" },
    { id: 9, name: "Transporte", icon: "🚗" },
    { id: 10, name: "Clima", icon: "🌤️" },
    { id: 11, name: "Viagens", icon: "✈️" },
    { id: 12, name: "Alfabeto e Verbos", icon: "🔤" },
    { id: 13, name: "Brinquedos", icon: "🛴" },
    { id: 14, name: "Dia, Meses e Estações", icon: "📅" },
    { id: 15, name: "Estados, Cidades e Regiões", icon: "🗺️" },
    { id: 16, name: "Feriados e Datas especiais", icon: "🎃"},
    { id: 17, name: "Itens de casa", icon: "🏠" },
    { id: 18, name: "Lugares turisticos e Públicos", icon: "🏛️" },
    { id: 19, name: "Números", icon: "🔢" },
    { id: 20, name: "Países", icon: "🌎" },
    { id: 21, name: "Corpo Humano", icon: "👨" },
    { id: 22, name: "Saúde", icon: "🩺" },
    { id: 23, name: "Religião", icon: "⛪" },
    { id: 24, name: "Times de Futebol", icon: "⚽" }
  ],
  "UsoTecnico": [
    { id: 25, name: "Esportes", icon: "⚽" },
    { id: 26, name: "Digital", icon: "📱" },   
    { id: 27, name: "Moda", icon: "👗" },                 
    { id: 28, name: "Ciência", icon: "🔬" },
    { id: 29, name: "Música", icon: "🎵" },
    { id: 30, name: "Arte", icon: "🖼️" },
    { id: 31, name: "Biologia", icon: "🐄" },
    { id: 32, name: "Geografia", icon: "🌍" },
    { id: 33, name: "Política", icon: "🏛️" },
    { id: 34, name: "História", icon: "📜" },
    { id: 35, name: "Saúde", icon: "🩺" },
    { id: 36, name: "Economia", icon: "💰" },
    { id: 37, name: "Psicologia", icon: "🧠" },
    { id: 38, name: "Religião", icon: "⛪" },
    { id: 39, name: "Literatura", icon: "📚" },
    { id: 40, name: "Filosofia", icon: "🤔" },
    { id: 41, name: "Programação", icon: "💻" },
    { id: 42, name: "Engenharia", icon: "🔧" },
    { id: 43, name: "Arquitetura", icon: "🏗️" },
    { id: 44, name: "Robótica", icon: "🤖" },
    { id: 45, name: "Matemática", icon: "➕" },
    { id: 46, name: "Química", icon: "⚗️" },
    { id: 47, name: "Física", icon: "📐" },
    { id: 48, name: "Astronomia", icon: "🌌" },
    { id: 49, name: "Letras", icon: "✍" },
    { id: 50, name: "Direito", icon: "⚖️" }
  ],
};

export default modulosData;